import type { Config } from 'dompurify'

export const MARKDOWN_PURIFY_CONFIG: Config = {
  ALLOWED_TAGS: [
    'a',
    'aside',
    'blockquote',
    'br',
    'code',
    'del',
    'div',
    'em',
    'h1',
    'h2',
    'h3',
    'h4',
    'h5',
    'h6',
    'hr',
    'li',
    'mark',
    'ol',
    'p',
    'pre',
    'section',
    'span',
    'strong',
    'sub',
    'sup',
    'table',
    'tbody',
    'td',
    'th',
    'thead',
    'tr',
    'ul',
  ],
  ALLOWED_ATTR: [
    'aria-label',
    'class',
    'data-callout',
    'href',
    'id',
    'rel',
    'title',
  ],
  ALLOW_DATA_ATTR: false,
  FORBID_TAGS: ['form', 'iframe', 'object', 'embed', 'script', 'style', 'link', 'meta'],
  FORBID_ATTR: ['onerror', 'onload', 'onclick', 'onmouseover', 'onfocus', 'onblur', 'style'],
}
